[package]
name = "snipaste"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.35.2"
crossbeam-channel = "0.5.8"
screenshots = "0.6.0"